### ISSUE TITLE
No map is rendered

### ISSUE THREAD

**Issue by CodingBobby** [dordenis/obsidian-map-gpx-plugin#1]
This is just the plugin I was searching for!

However, I don't get it to work – neither on my computer nor phone. I have installed it as you described [here](https://github.com/dordenis/obsidian-map-gpx-plugin?tab=readme-ov-file#install), and afterwards also installed the leaflet plugin because I thought it might be a dependency that is not loaded automatically. When inserting the code block, and changing to preview, it is just rendered as a normal markdown code block and no map appears.

Am I missing something here? Is there a setting elsewhere in Obsidian that I need to change?

Thanks!

**Comment by dordenis** [comment]
Thanks for your interest in the plugin.
The plugin is used by the internet map provider openstreetmap. if your Internet was turned off, you did not see the map.

I'll think about how to cache titles for offline work

**Comment by dordenis** [comment]
![Desktop-screenshot](https://github.com/dordenis/obsidian-map-gpx-plugin/assets/1261215/4bfd0806-835b-42ca-b4a0-94b98f671e3e)
Сheck that you have the plugin enabled

**Comment by CodingBobby** [comment]
Thanks for looking into this. I don't think that it has to do with my internet as I definitely have a connection.
Yes, the plugin appeared in the list and was automatically enabled after installation.

After reloading the plugins today, the update to 2.1.1 of your plugin was installed. Now, the code block is not rendered anymore and disappears. Instead, an empty div appeared. In the dev-tools I can see that there is a div created with contents that indicate that they do stem from your plugin. When I wanted to compare it with the source code, I found that in [`MapGps.ts`](https://github.com/dordenis/obsidian-map-gpx-plugin/blob/decf358b41eef526e0aa3ea0aa9d56cd37faee37/src/MapGpx.ts#L7C7-L7C7), you require the `./gpx` folder. I initially had something like `./Tracks/track.gpx` put into the code block as a path. When moving my track file to `./gpx/track.gpx` and just putting the track name without a path, everything worked!

Is there a reason you only look into the gpx-folder instead of just the entire vault (maybe security)? It looks like before you even had `../map/gpx` as a path for the track files required. I didn't find those paths used anywhere else, I wonder what it does. As you show how to use a paths other than `./gpx` in the documentation, is that behaviour even intended?

**Comment by dordenis** [comment]
[MapGps.ts](https://github.com/dordenis/obsidian-map-gpx-plugin/blob/decf358b41eef526e0aa3ea0aa9d56cd37faee37/src/MapGpx.ts#L7C7-L7C7) include [gpx.ts](https://github.com/dordenis/obsidian-map-gpx-plugin/blob/decf358b41eef526e0aa3ea0aa9d56cd37faee37/src/gpx.js)

You can specify any folder in your storage. Like this, specify relative path to file gpx
~~~markdown
```map
track: Tracks/track.gpx
```
~~~

For version 2.1.0 and higher, you can only specify the file name. The plugin will find the full path itself
~~~markdown
```map
track: track.gpx
```
~~~
